//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace beneDes.ServiceReferenceRDMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestConnectionRequest", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.SearchUserAppOrgListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.SearchAccountRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.CheckAccountRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.CheckGuidRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.GetFunsRequest))]
    public partial class TestConnectionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string validationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string validationCode {
            get {
                return this.validationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.validationCodeField, value) != true)) {
                    this.validationCodeField = value;
                    this.RaisePropertyChanged("validationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.requestIDField, value) != true)) {
                    this.requestIDField = value;
                    this.RaisePropertyChanged("requestID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchUserAppOrgListRequest", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class SearchUserAppOrgListRequest : beneDes.ServiceReferenceRDMS.TestConnectionRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouidField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                if ((object.ReferenceEquals(this.uidField, value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ouid {
            get {
                return this.ouidField;
            }
            set {
                if ((object.ReferenceEquals(this.ouidField, value) != true)) {
                    this.ouidField = value;
                    this.RaisePropertyChanged("ouid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchAccountRequest", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class SearchAccountRequest : beneDes.ServiceReferenceRDMS.TestConnectionRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private beneDes.ServiceReferenceRDMS.AccountInfo AccountInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public beneDes.ServiceReferenceRDMS.AccountInfo AccountInfo {
            get {
                return this.AccountInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountInfoField, value) != true)) {
                    this.AccountInfoField = value;
                    this.RaisePropertyChanged("AccountInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckAccountRequest", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class CheckAccountRequest : beneDes.ServiceReferenceRDMS.TestConnectionRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string domainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reservationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userPassword {
            get {
                return this.userPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.userPasswordField, value) != true)) {
                    this.userPasswordField = value;
                    this.RaisePropertyChanged("userPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                if ((object.ReferenceEquals(this.domainField, value) != true)) {
                    this.domainField = value;
                    this.RaisePropertyChanged("domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reservation {
            get {
                return this.reservationField;
            }
            set {
                if ((object.ReferenceEquals(this.reservationField, value) != true)) {
                    this.reservationField = value;
                    this.RaisePropertyChanged("reservation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckGuidRequest", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class CheckGuidRequest : beneDes.ServiceReferenceRDMS.TestConnectionRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userGuid {
            get {
                return this.userGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.userGuidField, value) != true)) {
                    this.userGuidField = value;
                    this.RaisePropertyChanged("userGuid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFunsRequest", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class GetFunsRequest : beneDes.ServiceReferenceRDMS.TestConnectionRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string funIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userGuid {
            get {
                return this.userGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.userGuidField, value) != true)) {
                    this.userGuidField = value;
                    this.RaisePropertyChanged("userGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string funID {
            get {
                return this.funIDField;
            }
            set {
                if ((object.ReferenceEquals(this.funIDField, value) != true)) {
                    this.funIDField = value;
                    this.RaisePropertyChanged("funID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPCCommonGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPCCommonJobNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPCCommonMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPCCommonOrgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPCCommonPostionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPCEmployeeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPCisManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string displayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employeeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string homePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ouidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string domainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPCCommonGender {
            get {
                return this.CNPCCommonGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPCCommonGenderField, value) != true)) {
                    this.CNPCCommonGenderField = value;
                    this.RaisePropertyChanged("CNPCCommonGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPCCommonJobName {
            get {
                return this.CNPCCommonJobNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPCCommonJobNameField, value) != true)) {
                    this.CNPCCommonJobNameField = value;
                    this.RaisePropertyChanged("CNPCCommonJobName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPCCommonMobile {
            get {
                return this.CNPCCommonMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPCCommonMobileField, value) != true)) {
                    this.CNPCCommonMobileField = value;
                    this.RaisePropertyChanged("CNPCCommonMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPCCommonOrg {
            get {
                return this.CNPCCommonOrgField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPCCommonOrgField, value) != true)) {
                    this.CNPCCommonOrgField = value;
                    this.RaisePropertyChanged("CNPCCommonOrg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPCCommonPostion {
            get {
                return this.CNPCCommonPostionField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPCCommonPostionField, value) != true)) {
                    this.CNPCCommonPostionField = value;
                    this.RaisePropertyChanged("CNPCCommonPostion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPCEmployeeNumber {
            get {
                return this.CNPCEmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPCEmployeeNumberField, value) != true)) {
                    this.CNPCEmployeeNumberField = value;
                    this.RaisePropertyChanged("CNPCEmployeeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNPCisManager {
            get {
                return this.CNPCisManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPCisManagerField, value) != true)) {
                    this.CNPCisManagerField = value;
                    this.RaisePropertyChanged("CNPCisManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cn {
            get {
                return this.cnField;
            }
            set {
                if ((object.ReferenceEquals(this.cnField, value) != true)) {
                    this.cnField = value;
                    this.RaisePropertyChanged("cn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.displayNameField, value) != true)) {
                    this.displayNameField = value;
                    this.RaisePropertyChanged("displayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string employeeType {
            get {
                return this.employeeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeTypeField, value) != true)) {
                    this.employeeTypeField = value;
                    this.RaisePropertyChanged("employeeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                if ((object.ReferenceEquals(this.uidField, value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string homePhone {
            get {
                return this.homePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.homePhoneField, value) != true)) {
                    this.homePhoneField = value;
                    this.RaisePropertyChanged("homePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ouid {
            get {
                return this.ouidField;
            }
            set {
                if ((object.ReferenceEquals(this.ouidField, value) != true)) {
                    this.ouidField = value;
                    this.RaisePropertyChanged("ouid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                if ((object.ReferenceEquals(this.domainField, value) != true)) {
                    this.domainField = value;
                    this.RaisePropertyChanged("domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string accountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.accountStatusField, value) != true)) {
                    this.accountStatusField = value;
                    this.RaisePropertyChanged("accountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestConnectionResponse", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.SearchUserAppOrgListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.SearchAccountResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.CheckGuidResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(beneDes.ServiceReferenceRDMS.GetFunsResponse))]
    public partial class TestConnectionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestIDField;
        
        private bool returnFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.requestIDField, value) != true)) {
                    this.requestIDField = value;
                    this.RaisePropertyChanged("requestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool returnFlag {
            get {
                return this.returnFlagField;
            }
            set {
                if ((this.returnFlagField.Equals(value) != true)) {
                    this.returnFlagField = value;
                    this.RaisePropertyChanged("returnFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.returnCodeField, value) != true)) {
                    this.returnCodeField = value;
                    this.RaisePropertyChanged("returnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.returnMessageField, value) != true)) {
                    this.returnMessageField = value;
                    this.RaisePropertyChanged("returnMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchUserAppOrgListResponse", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class SearchUserAppOrgListResponse : beneDes.ServiceReferenceRDMS.TestConnectionResponse {
        
        private int appOrgInfoSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private beneDes.ServiceReferenceRDMS.AppOrgInfo[] appOrgInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int appOrgInfoSize {
            get {
                return this.appOrgInfoSizeField;
            }
            set {
                if ((this.appOrgInfoSizeField.Equals(value) != true)) {
                    this.appOrgInfoSizeField = value;
                    this.RaisePropertyChanged("appOrgInfoSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public beneDes.ServiceReferenceRDMS.AppOrgInfo[] appOrgInfoList {
            get {
                return this.appOrgInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.appOrgInfoListField, value) != true)) {
                    this.appOrgInfoListField = value;
                    this.RaisePropertyChanged("appOrgInfoList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchAccountResponse", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class SearchAccountResponse : beneDes.ServiceReferenceRDMS.TestConnectionResponse {
        
        private int accountInfoSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private beneDes.ServiceReferenceRDMS.AccountInfo[] accountInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int accountInfoSize {
            get {
                return this.accountInfoSizeField;
            }
            set {
                if ((this.accountInfoSizeField.Equals(value) != true)) {
                    this.accountInfoSizeField = value;
                    this.RaisePropertyChanged("accountInfoSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public beneDes.ServiceReferenceRDMS.AccountInfo[] accountInfoList {
            get {
                return this.accountInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.accountInfoListField, value) != true)) {
                    this.accountInfoListField = value;
                    this.RaisePropertyChanged("accountInfoList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckGuidResponse", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class CheckGuidResponse : beneDes.ServiceReferenceRDMS.TestConnectionResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orgIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string loginName {
            get {
                return this.loginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.loginNameField, value) != true)) {
                    this.loginNameField = value;
                    this.RaisePropertyChanged("loginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orgName {
            get {
                return this.orgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.orgNameField, value) != true)) {
                    this.orgNameField = value;
                    this.RaisePropertyChanged("orgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string orgID {
            get {
                return this.orgIDField;
            }
            set {
                if ((object.ReferenceEquals(this.orgIDField, value) != true)) {
                    this.orgIDField = value;
                    this.RaisePropertyChanged("orgID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFunsResponse", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class GetFunsResponse : beneDes.ServiceReferenceRDMS.TestConnectionResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private beneDes.ServiceReferenceRDMS.FunInfo[] FunsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public beneDes.ServiceReferenceRDMS.FunInfo[] Funs {
            get {
                return this.FunsField;
            }
            set {
                if ((object.ReferenceEquals(this.FunsField, value) != true)) {
                    this.FunsField = value;
                    this.RaisePropertyChanged("Funs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppOrgInfo", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class AppOrgInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appOrgIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appOrgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appOrgParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appOrgPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appOrgID {
            get {
                return this.appOrgIDField;
            }
            set {
                if ((object.ReferenceEquals(this.appOrgIDField, value) != true)) {
                    this.appOrgIDField = value;
                    this.RaisePropertyChanged("appOrgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appOrgName {
            get {
                return this.appOrgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.appOrgNameField, value) != true)) {
                    this.appOrgNameField = value;
                    this.RaisePropertyChanged("appOrgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appOrgParentID {
            get {
                return this.appOrgParentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.appOrgParentIDField, value) != true)) {
                    this.appOrgParentIDField = value;
                    this.RaisePropertyChanged("appOrgParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appOrgPath {
            get {
                return this.appOrgPathField;
            }
            set {
                if ((object.ReferenceEquals(this.appOrgPathField, value) != true)) {
                    this.appOrgPathField = value;
                    this.RaisePropertyChanged("appOrgPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunInfo", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class FunInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string P_F_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fun_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICONField;
        
        private int SORT_SEQUENCEField;
        
        private bool IsHaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private beneDes.ServiceReferenceRDMS.RWINFO[] RWSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string F_ID {
            get {
                return this.F_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.F_IDField, value) != true)) {
                    this.F_IDField = value;
                    this.RaisePropertyChanged("F_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string P_F_ID {
            get {
                return this.P_F_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.P_F_IDField, value) != true)) {
                    this.P_F_IDField = value;
                    this.RaisePropertyChanged("P_F_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Fun_Name {
            get {
                return this.Fun_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Fun_NameField, value) != true)) {
                    this.Fun_NameField = value;
                    this.RaisePropertyChanged("Fun_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ICON {
            get {
                return this.ICONField;
            }
            set {
                if ((object.ReferenceEquals(this.ICONField, value) != true)) {
                    this.ICONField = value;
                    this.RaisePropertyChanged("ICON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SORT_SEQUENCE {
            get {
                return this.SORT_SEQUENCEField;
            }
            set {
                if ((this.SORT_SEQUENCEField.Equals(value) != true)) {
                    this.SORT_SEQUENCEField = value;
                    this.RaisePropertyChanged("SORT_SEQUENCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsHave {
            get {
                return this.IsHaveField;
            }
            set {
                if ((this.IsHaveField.Equals(value) != true)) {
                    this.IsHaveField = value;
                    this.RaisePropertyChanged("IsHave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public beneDes.ServiceReferenceRDMS.RWINFO[] RWS {
            get {
                return this.RWSField;
            }
            set {
                if ((object.ReferenceEquals(this.RWSField, value) != true)) {
                    this.RWSField = value;
                    this.RaisePropertyChanged("RWS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RWINFO", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class RWINFO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckAccountResponse", Namespace="http://10.78.56.9/")]
    [System.SerializableAttribute()]
    public partial class CheckAccountResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestIDField;
        
        private bool returnFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.requestIDField, value) != true)) {
                    this.requestIDField = value;
                    this.RaisePropertyChanged("requestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool returnFlag {
            get {
                return this.returnFlagField;
            }
            set {
                if ((this.returnFlagField.Equals(value) != true)) {
                    this.returnFlagField = value;
                    this.RaisePropertyChanged("returnFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.returnMessageField, value) != true)) {
                    this.returnMessageField = value;
                    this.RaisePropertyChanged("returnMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.78.56.9/", ConfigurationName="ServiceReferenceRDMS.RDMSAccountWebServiceSoap")]
    public interface RDMSAccountWebServiceSoap {
        
        // CODEGEN: 命名空间 http://10.78.56.9/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.78.56.9/testConnection", ReplyAction="*")]
        beneDes.ServiceReferenceRDMS.testConnectionResponse1 testConnection(beneDes.ServiceReferenceRDMS.testConnectionRequest1 request);
        
        // CODEGEN: 命名空间 http://10.78.56.9/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.78.56.9/searchUserAppOrgList", ReplyAction="*")]
        beneDes.ServiceReferenceRDMS.searchUserAppOrgListResponse1 searchUserAppOrgList(beneDes.ServiceReferenceRDMS.searchUserAppOrgListRequest1 request);
        
        // CODEGEN: 命名空间 http://10.78.56.9/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.78.56.9/searchAccount", ReplyAction="*")]
        beneDes.ServiceReferenceRDMS.searchAccountResponse1 searchAccount(beneDes.ServiceReferenceRDMS.searchAccountRequest1 request);
        
        // CODEGEN: 命名空间 http://10.78.56.9/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.78.56.9/checkAccount", ReplyAction="*")]
        beneDes.ServiceReferenceRDMS.checkAccountResponse1 checkAccount(beneDes.ServiceReferenceRDMS.checkAccountRequest1 request);
        
        // CODEGEN: 命名空间 http://10.78.56.9/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.78.56.9/checkGuid", ReplyAction="*")]
        beneDes.ServiceReferenceRDMS.checkGuidResponse1 checkGuid(beneDes.ServiceReferenceRDMS.checkGuidRequest1 request);
        
        // CODEGEN: 命名空间 http://10.78.56.9/ 的元素名称 request 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://10.78.56.9/getFuns", ReplyAction="*")]
        beneDes.ServiceReferenceRDMS.getFunsResponse1 getFuns(beneDes.ServiceReferenceRDMS.getFunsRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testConnectionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testConnection", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.testConnectionRequest1Body Body;
        
        public testConnectionRequest1() {
        }
        
        public testConnectionRequest1(beneDes.ServiceReferenceRDMS.testConnectionRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class testConnectionRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.TestConnectionRequest request;
        
        public testConnectionRequest1Body() {
        }
        
        public testConnectionRequest1Body(beneDes.ServiceReferenceRDMS.TestConnectionRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testConnectionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testConnectionResponse", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.testConnectionResponse1Body Body;
        
        public testConnectionResponse1() {
        }
        
        public testConnectionResponse1(beneDes.ServiceReferenceRDMS.testConnectionResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class testConnectionResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.TestConnectionResponse testConnectionResult;
        
        public testConnectionResponse1Body() {
        }
        
        public testConnectionResponse1Body(beneDes.ServiceReferenceRDMS.TestConnectionResponse testConnectionResult) {
            this.testConnectionResult = testConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchUserAppOrgListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchUserAppOrgList", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.searchUserAppOrgListRequest1Body Body;
        
        public searchUserAppOrgListRequest1() {
        }
        
        public searchUserAppOrgListRequest1(beneDes.ServiceReferenceRDMS.searchUserAppOrgListRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class searchUserAppOrgListRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.SearchUserAppOrgListRequest request;
        
        public searchUserAppOrgListRequest1Body() {
        }
        
        public searchUserAppOrgListRequest1Body(beneDes.ServiceReferenceRDMS.SearchUserAppOrgListRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchUserAppOrgListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchUserAppOrgListResponse", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.searchUserAppOrgListResponse1Body Body;
        
        public searchUserAppOrgListResponse1() {
        }
        
        public searchUserAppOrgListResponse1(beneDes.ServiceReferenceRDMS.searchUserAppOrgListResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class searchUserAppOrgListResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.SearchUserAppOrgListResponse searchUserAppOrgListResult;
        
        public searchUserAppOrgListResponse1Body() {
        }
        
        public searchUserAppOrgListResponse1Body(beneDes.ServiceReferenceRDMS.SearchUserAppOrgListResponse searchUserAppOrgListResult) {
            this.searchUserAppOrgListResult = searchUserAppOrgListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchAccountRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchAccount", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.searchAccountRequest1Body Body;
        
        public searchAccountRequest1() {
        }
        
        public searchAccountRequest1(beneDes.ServiceReferenceRDMS.searchAccountRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class searchAccountRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.SearchAccountRequest request;
        
        public searchAccountRequest1Body() {
        }
        
        public searchAccountRequest1Body(beneDes.ServiceReferenceRDMS.SearchAccountRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchAccountResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchAccountResponse", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.searchAccountResponse1Body Body;
        
        public searchAccountResponse1() {
        }
        
        public searchAccountResponse1(beneDes.ServiceReferenceRDMS.searchAccountResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class searchAccountResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.SearchAccountResponse searchAccountResult;
        
        public searchAccountResponse1Body() {
        }
        
        public searchAccountResponse1Body(beneDes.ServiceReferenceRDMS.SearchAccountResponse searchAccountResult) {
            this.searchAccountResult = searchAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkAccountRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkAccount", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.checkAccountRequest1Body Body;
        
        public checkAccountRequest1() {
        }
        
        public checkAccountRequest1(beneDes.ServiceReferenceRDMS.checkAccountRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class checkAccountRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.CheckAccountRequest request;
        
        public checkAccountRequest1Body() {
        }
        
        public checkAccountRequest1Body(beneDes.ServiceReferenceRDMS.CheckAccountRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkAccountResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkAccountResponse", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.checkAccountResponse1Body Body;
        
        public checkAccountResponse1() {
        }
        
        public checkAccountResponse1(beneDes.ServiceReferenceRDMS.checkAccountResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class checkAccountResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.CheckAccountResponse checkAccountResult;
        
        public checkAccountResponse1Body() {
        }
        
        public checkAccountResponse1Body(beneDes.ServiceReferenceRDMS.CheckAccountResponse checkAccountResult) {
            this.checkAccountResult = checkAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkGuidRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkGuid", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.checkGuidRequest1Body Body;
        
        public checkGuidRequest1() {
        }
        
        public checkGuidRequest1(beneDes.ServiceReferenceRDMS.checkGuidRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class checkGuidRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.CheckGuidRequest request;
        
        public checkGuidRequest1Body() {
        }
        
        public checkGuidRequest1Body(beneDes.ServiceReferenceRDMS.CheckGuidRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkGuidResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkGuidResponse", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.checkGuidResponse1Body Body;
        
        public checkGuidResponse1() {
        }
        
        public checkGuidResponse1(beneDes.ServiceReferenceRDMS.checkGuidResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class checkGuidResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.CheckGuidResponse checkGuidResult;
        
        public checkGuidResponse1Body() {
        }
        
        public checkGuidResponse1Body(beneDes.ServiceReferenceRDMS.CheckGuidResponse checkGuidResult) {
            this.checkGuidResult = checkGuidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFunsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFuns", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.getFunsRequest1Body Body;
        
        public getFunsRequest1() {
        }
        
        public getFunsRequest1(beneDes.ServiceReferenceRDMS.getFunsRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class getFunsRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.GetFunsRequest request;
        
        public getFunsRequest1Body() {
        }
        
        public getFunsRequest1Body(beneDes.ServiceReferenceRDMS.GetFunsRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFunsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFunsResponse", Namespace="http://10.78.56.9/", Order=0)]
        public beneDes.ServiceReferenceRDMS.getFunsResponse1Body Body;
        
        public getFunsResponse1() {
        }
        
        public getFunsResponse1(beneDes.ServiceReferenceRDMS.getFunsResponse1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.78.56.9/")]
    public partial class getFunsResponse1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public beneDes.ServiceReferenceRDMS.GetFunsResponse getFunsResult;
        
        public getFunsResponse1Body() {
        }
        
        public getFunsResponse1Body(beneDes.ServiceReferenceRDMS.GetFunsResponse getFunsResult) {
            this.getFunsResult = getFunsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RDMSAccountWebServiceSoapChannel : beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RDMSAccountWebServiceSoapClient : System.ServiceModel.ClientBase<beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap>, beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap {
        
        public RDMSAccountWebServiceSoapClient() {
        }
        
        public RDMSAccountWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RDMSAccountWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDMSAccountWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RDMSAccountWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        beneDes.ServiceReferenceRDMS.testConnectionResponse1 beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap.testConnection(beneDes.ServiceReferenceRDMS.testConnectionRequest1 request) {
            return base.Channel.testConnection(request);
        }
        
        public beneDes.ServiceReferenceRDMS.TestConnectionResponse testConnection(beneDes.ServiceReferenceRDMS.TestConnectionRequest request) {
            beneDes.ServiceReferenceRDMS.testConnectionRequest1 inValue = new beneDes.ServiceReferenceRDMS.testConnectionRequest1();
            inValue.Body = new beneDes.ServiceReferenceRDMS.testConnectionRequest1Body();
            inValue.Body.request = request;
            beneDes.ServiceReferenceRDMS.testConnectionResponse1 retVal = ((beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap)(this)).testConnection(inValue);
            return retVal.Body.testConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        beneDes.ServiceReferenceRDMS.searchUserAppOrgListResponse1 beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap.searchUserAppOrgList(beneDes.ServiceReferenceRDMS.searchUserAppOrgListRequest1 request) {
            return base.Channel.searchUserAppOrgList(request);
        }
        
        public beneDes.ServiceReferenceRDMS.SearchUserAppOrgListResponse searchUserAppOrgList(beneDes.ServiceReferenceRDMS.SearchUserAppOrgListRequest request) {
            beneDes.ServiceReferenceRDMS.searchUserAppOrgListRequest1 inValue = new beneDes.ServiceReferenceRDMS.searchUserAppOrgListRequest1();
            inValue.Body = new beneDes.ServiceReferenceRDMS.searchUserAppOrgListRequest1Body();
            inValue.Body.request = request;
            beneDes.ServiceReferenceRDMS.searchUserAppOrgListResponse1 retVal = ((beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap)(this)).searchUserAppOrgList(inValue);
            return retVal.Body.searchUserAppOrgListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        beneDes.ServiceReferenceRDMS.searchAccountResponse1 beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap.searchAccount(beneDes.ServiceReferenceRDMS.searchAccountRequest1 request) {
            return base.Channel.searchAccount(request);
        }
        
        public beneDes.ServiceReferenceRDMS.SearchAccountResponse searchAccount(beneDes.ServiceReferenceRDMS.SearchAccountRequest request) {
            beneDes.ServiceReferenceRDMS.searchAccountRequest1 inValue = new beneDes.ServiceReferenceRDMS.searchAccountRequest1();
            inValue.Body = new beneDes.ServiceReferenceRDMS.searchAccountRequest1Body();
            inValue.Body.request = request;
            beneDes.ServiceReferenceRDMS.searchAccountResponse1 retVal = ((beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap)(this)).searchAccount(inValue);
            return retVal.Body.searchAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        beneDes.ServiceReferenceRDMS.checkAccountResponse1 beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap.checkAccount(beneDes.ServiceReferenceRDMS.checkAccountRequest1 request) {
            return base.Channel.checkAccount(request);
        }
        
        public beneDes.ServiceReferenceRDMS.CheckAccountResponse checkAccount(beneDes.ServiceReferenceRDMS.CheckAccountRequest request) {
            beneDes.ServiceReferenceRDMS.checkAccountRequest1 inValue = new beneDes.ServiceReferenceRDMS.checkAccountRequest1();
            inValue.Body = new beneDes.ServiceReferenceRDMS.checkAccountRequest1Body();
            inValue.Body.request = request;
            beneDes.ServiceReferenceRDMS.checkAccountResponse1 retVal = ((beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap)(this)).checkAccount(inValue);
            return retVal.Body.checkAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        beneDes.ServiceReferenceRDMS.checkGuidResponse1 beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap.checkGuid(beneDes.ServiceReferenceRDMS.checkGuidRequest1 request) {
            return base.Channel.checkGuid(request);
        }
        
        public beneDes.ServiceReferenceRDMS.CheckGuidResponse checkGuid(beneDes.ServiceReferenceRDMS.CheckGuidRequest request) {
            beneDes.ServiceReferenceRDMS.checkGuidRequest1 inValue = new beneDes.ServiceReferenceRDMS.checkGuidRequest1();
            inValue.Body = new beneDes.ServiceReferenceRDMS.checkGuidRequest1Body();
            inValue.Body.request = request;
            beneDes.ServiceReferenceRDMS.checkGuidResponse1 retVal = ((beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap)(this)).checkGuid(inValue);
            return retVal.Body.checkGuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        beneDes.ServiceReferenceRDMS.getFunsResponse1 beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap.getFuns(beneDes.ServiceReferenceRDMS.getFunsRequest1 request) {
            return base.Channel.getFuns(request);
        }
        
        public beneDes.ServiceReferenceRDMS.GetFunsResponse getFuns(beneDes.ServiceReferenceRDMS.GetFunsRequest request) {
            beneDes.ServiceReferenceRDMS.getFunsRequest1 inValue = new beneDes.ServiceReferenceRDMS.getFunsRequest1();
            inValue.Body = new beneDes.ServiceReferenceRDMS.getFunsRequest1Body();
            inValue.Body.request = request;
            beneDes.ServiceReferenceRDMS.getFunsResponse1 retVal = ((beneDes.ServiceReferenceRDMS.RDMSAccountWebServiceSoap)(this)).getFuns(inValue);
            return retVal.Body.getFunsResult;
        }
    }
}
